module.exports = [
    "http://bj.lianjia.com/ershoufang/shilibao/l2a4/",
    "http://bj.lianjia.com/ershoufang/shilibao/pg2l2a4/",
    "http://bj.5i5j.com/exchange/shilibao/r2",
    "http://bj.5i5j.com/exchange/shilibao/r2n2",
    "http://bj.5i5j.com/exchange/shilibao/r2n3",
    "http://bj.5i5j.com/exchange/shilibao/r2n4",
    "http://bj.5i5j.com/exchange/shilibao/r2n5",
    "http://bj.5i5j.com/exchange/shilibao/r2n6",
    "http://www.iwjw.com/sale/beijing/g2id13633rn2",
    "http://www.iwjw.com/sale/beijing/g2id13633rn2p2",
    "http://esf.fang.com/house/g22-kw%ca%ae%c0%ef%b1%a4/",
    "http://esf.fang.com/house/g22-i32-kw%ca%ae%c0%ef%b1%a4/",
    "http://esf.fang.com/house/g22-i33-kw%ca%ae%c0%ef%b1%a4/",
    "http://esf.fang.com/house/g22-i34-kw%ca%ae%c0%ef%b1%a4/",
    "http://esf.fang.com/house/g22-i35-kw%ca%ae%c0%ef%b1%a4/",
];
