module.exports = [
    "http://bj.lianjia.com/ershoufang/shilibao/l2a4/",
    "http://bj.lianjia.com/ershoufang/shilibao/pg2l2a4/",
    "http://bj.5i5j.com/exchange/shilibao/r2",
    "http://bj.5i5j.com/exchange/shilibao/r2n2",
    "http://bj.5i5j.com/exchange/shilibao/r2n3",
    "http://bj.5i5j.com/exchange/shilibao/r2n4",
    "http://bj.5i5j.com/exchange/shilibao/r2n5",
    "http://bj.5i5j.com/exchange/shilibao/r2n6",
    "http://bj.5i5j.com/exchange/shilibao/r2n7",
    "http://bj.5i5j.com/exchange/shilibao/r2n8",
    "http://bj.5i5j.com/exchange/shilibao/r2n9",
    "http://bj.5i5j.com/exchange/shilibao/r2n10",
    "http://www.iwjw.com/sale/beijing/g2id13633rn2",
    "http://www.iwjw.com/sale/beijing/g2id13633rn2p2",
];
